services:
  backend:
    image: ${DOCKER_USERNAME}/docker-project-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
    ports:
      - ${BACKEND_PORT:-8081}:8081
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.3'
          memory: 64M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 5
    profiles:
      - prod
    networks:
      - app-network
  
  backend_dev:
    image: ${DOCKER_USERNAME}/docker-project-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
    ports:
      - ${BACKEND_PORT:-8081}:8081
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 100M
        reservations:
          cpus: '0.2'
          memory: 64M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      mode: replicated
      replicas: 3
    profiles:
      - dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge