services:
  backend:
    image: ${DOCKER_USERNAME}/docker-project-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
    ports:
      - ${BACKEND_PORT:-8081}:8081
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8081/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge